displayName=Custom Weapon SFX
author=H-Mill
description=Plays a custom sound effect on configurable player actions
tags=custom,weapon,sound,sfx,squeaky,toy
version=2.0
plugins=com.customweaponsfx.CustomWeaponSfxPlugin
build=standard
